### ISSUE TITLE
Deploying on other platforms

### ISSUE THREAD

**Issue by cmakelabs** [arplaboratory/learning-to-fly#11]
Thanks for the excellent work, currently for my research I am using PX4 on a small custom quadrotor. I am wondering what steps are required to deploy `learning to fly` models, to my small rotor. Can I directly deploy it on the flight controller?

**Comment by jonas-eschmann** [comment]
Hi @cmakelabs,

Yes, you can directly flash it into the PX4 flight controller. The process would be something like this:

1. System identification (e.g. using [https://sysid.tools](https://sysid.tools))
2. Train a policy based on the identified parameters
3. Use [https://github.com/rl-tools/px4/](https://github.com/rl-tools/px4/) to compile the checkpoint into the firmware
