### ISSUE TITLE
KeyError: 'motor_warmup

### ISSUE THREAD

**Issue by nishuzumi** [arplaboratory/learning-to-fly#8]
Can not start the script

❯ python3 scripts/trigger.py --mode hover_learned
Parameter rlt.trigger was 0, setting to 0
Parameter rlt.trigger is 0 now
Parameter rlt.wn was 1, setting to 1
Parameter rlt.wn is 1 now
Traceback (most recent call last):
  File "/Users/box/code/rust/learning_to_fly/scripts/trigger.py", line 162, in <module>
    mode_hover_learned(scf.cf, args)
  File "/Users/box/code/rust/learning_to_fly/scripts/trigger.py", line 51, in mode_hover_learned
    set_param(cf, "rlt.motor_warmup", 1)
  File "/Users/box/code/rust/learning_to_fly/scripts/trigger.py", line 72, in set_param
    print(f"Parameter {name} was {cf.param.get_value(name)}, setting to {target}")
  File "/Users/box/Library/Python/3.9/lib/python/site-packages/cflib/crazyflie/param.py", line 381, in get_value
    return self.values[group][name]
KeyError: 'motor_warmup'

**Comment by jonas-eschmann** [comment]
Hi @nishuzumi 
good point! I can't test it right now, but it looks like the controller submodule is one commit too far behind. My guess is that if you checkout `d52b11a03caa1dadaf6b6bf02f328719b5bdd215` and re-compile & flash the firmware it should work. I'll hopefully get to test it soon and bump the submodule
Let me know how it goes!

**Comment by AI4IS** [comment]
Hi @jonas-eschmann 
I have a same problem. However, I can't find `d52b11a03caa1dadaf6b6bf02f328719b5bdd215` branch of controller submodule.

**Comment by jonas-eschmann** [comment]
Hi @AI4IS!

You can find the commit here: [https://github.com/arplaboratory/learning_to_fly_controller/commit/d52b11a03caa1dadaf6b6bf02f328719b5bdd215](https://github.com/arplaboratory/learning_to_fly_controller/commit/d52b11a03caa1dadaf6b6bf02f328719b5bdd215)

something like:
```
cd controller
git fetch
git checkout d52b11a03caa1dadaf6b6bf02f328719b5bdd215
```
should work.

Let me know if it works for you! If you can confirm that it works I will bump the commit so that ` d52b11a03caa1dadaf6b6bf02f328719b5bdd215` is the default

**Comment by AI4IS** [comment]
Thank you @jonas-eschmann !
I have tried this commit and finally it worked for me! Everything is working well. I don't have any further problem.

**Comment by jonas-eschmann** [comment]
@AI4IS great to hear that and thanks for confirming! 
I'll bump the commit of the submodule then such that it is the default
